/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as GerenciaRouteImport } from './routes/gerencia'
import { Route as CorretorRouteImport } from './routes/corretor'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedRoletaRouteImport } from './routes/_authenticated/roleta'
import { Route as AuthenticatedPlantoesRouteImport } from './routes/_authenticated/plantoes'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedEmpreendimentosRouteImport } from './routes/_authenticated/empreendimentos'
import { Route as AuthenticatedCorretoresRouteImport } from './routes/_authenticated/corretores'
import { Route as AuthenticatedAtendimentosRouteImport } from './routes/_authenticated/atendimentos'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiPublicLorenzaRouteImport } from './routes/api/public/lorenza'
import { Route as ApiPublicHooksAvisosRenovacaoRouteImport } from './routes/api/public/hooks/avisos-renovacao'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciaRoute = GerenciaRouteImport.update({
  id: '/gerencia',
  path: '/gerencia',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorRoute = CorretorRouteImport.update({
  id: '/corretor',
  path: '/corretor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoletaRoute = AuthenticatedRoletaRouteImport.update({
  id: '/roleta',
  path: '/roleta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlantoesRoute = AuthenticatedPlantoesRouteImport.update({
  id: '/plantoes',
  path: '/plantoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpreendimentosRoute =
  AuthenticatedEmpreendimentosRouteImport.update({
    id: '/empreendimentos',
    path: '/empreendimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCorretoresRoute = AuthenticatedCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtendimentosRoute =
  AuthenticatedAtendimentosRouteImport.update({
    id: '/atendimentos',
    path: '/atendimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicLorenzaRoute = ApiPublicLorenzaRouteImport.update({
  id: '/api/public/lorenza',
  path: '/api/public/lorenza',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAvisosRenovacaoRoute =
  ApiPublicHooksAvisosRenovacaoRouteImport.update({
    id: '/api/public/hooks/avisos-renovacao',
    path: '/api/public/hooks/avisos-renovacao',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corretor': typeof CorretorRoute
  '/gerencia': typeof GerenciaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/setup': typeof SetupRoute
  '/app': typeof AuthenticatedAppRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/plantoes': typeof AuthenticatedPlantoesRoute
  '/roleta': typeof AuthenticatedRoletaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/lorenza': typeof ApiPublicLorenzaRoute
  '/api/public/hooks/avisos-renovacao': typeof ApiPublicHooksAvisosRenovacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corretor': typeof CorretorRoute
  '/gerencia': typeof GerenciaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/setup': typeof SetupRoute
  '/app': typeof AuthenticatedAppRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/plantoes': typeof AuthenticatedPlantoesRoute
  '/roleta': typeof AuthenticatedRoletaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/lorenza': typeof ApiPublicLorenzaRoute
  '/api/public/hooks/avisos-renovacao': typeof ApiPublicHooksAvisosRenovacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/corretor': typeof CorretorRoute
  '/gerencia': typeof GerenciaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/setup': typeof SetupRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/_authenticated/corretores': typeof AuthenticatedCorretoresRoute
  '/_authenticated/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/plantoes': typeof AuthenticatedPlantoesRoute
  '/_authenticated/roleta': typeof AuthenticatedRoletaRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/lorenza': typeof ApiPublicLorenzaRoute
  '/api/public/hooks/avisos-renovacao': typeof ApiPublicHooksAvisosRenovacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corretor'
    | '/gerencia'
    | '/lgpd'
    | '/login'
    | '/planos'
    | '/setup'
    | '/app'
    | '/atendimentos'
    | '/corretores'
    | '/empreendimentos'
    | '/integracoes'
    | '/plantoes'
    | '/roleta'
    | '/usuarios'
    | '/api/public/lorenza'
    | '/api/public/hooks/avisos-renovacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corretor'
    | '/gerencia'
    | '/lgpd'
    | '/login'
    | '/planos'
    | '/setup'
    | '/app'
    | '/atendimentos'
    | '/corretores'
    | '/empreendimentos'
    | '/integracoes'
    | '/plantoes'
    | '/roleta'
    | '/usuarios'
    | '/api/public/lorenza'
    | '/api/public/hooks/avisos-renovacao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/corretor'
    | '/gerencia'
    | '/lgpd'
    | '/login'
    | '/planos'
    | '/setup'
    | '/_authenticated/app'
    | '/_authenticated/atendimentos'
    | '/_authenticated/corretores'
    | '/_authenticated/empreendimentos'
    | '/_authenticated/integracoes'
    | '/_authenticated/plantoes'
    | '/_authenticated/roleta'
    | '/_authenticated/usuarios'
    | '/api/public/lorenza'
    | '/api/public/hooks/avisos-renovacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CorretorRoute: typeof CorretorRoute
  GerenciaRoute: typeof GerenciaRoute
  LgpdRoute: typeof LgpdRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  SetupRoute: typeof SetupRoute
  ApiPublicLorenzaRoute: typeof ApiPublicLorenzaRoute
  ApiPublicHooksAvisosRenovacaoRoute: typeof ApiPublicHooksAvisosRenovacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencia': {
      id: '/gerencia'
      path: '/gerencia'
      fullPath: '/gerencia'
      preLoaderRoute: typeof GerenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor': {
      id: '/corretor'
      path: '/corretor'
      fullPath: '/corretor'
      preLoaderRoute: typeof CorretorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roleta': {
      id: '/_authenticated/roleta'
      path: '/roleta'
      fullPath: '/roleta'
      preLoaderRoute: typeof AuthenticatedRoletaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plantoes': {
      id: '/_authenticated/plantoes'
      path: '/plantoes'
      fullPath: '/plantoes'
      preLoaderRoute: typeof AuthenticatedPlantoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empreendimentos': {
      id: '/_authenticated/empreendimentos'
      path: '/empreendimentos'
      fullPath: '/empreendimentos'
      preLoaderRoute: typeof AuthenticatedEmpreendimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corretores': {
      id: '/_authenticated/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AuthenticatedCorretoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atendimentos': {
      id: '/_authenticated/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AuthenticatedAtendimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/lorenza': {
      id: '/api/public/lorenza'
      path: '/api/public/lorenza'
      fullPath: '/api/public/lorenza'
      preLoaderRoute: typeof ApiPublicLorenzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/avisos-renovacao': {
      id: '/api/public/hooks/avisos-renovacao'
      path: '/api/public/hooks/avisos-renovacao'
      fullPath: '/api/public/hooks/avisos-renovacao'
      preLoaderRoute: typeof ApiPublicHooksAvisosRenovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedAtendimentosRoute: typeof AuthenticatedAtendimentosRoute
  AuthenticatedCorretoresRoute: typeof AuthenticatedCorretoresRoute
  AuthenticatedEmpreendimentosRoute: typeof AuthenticatedEmpreendimentosRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedPlantoesRoute: typeof AuthenticatedPlantoesRoute
  AuthenticatedRoletaRoute: typeof AuthenticatedRoletaRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedAtendimentosRoute: AuthenticatedAtendimentosRoute,
  AuthenticatedCorretoresRoute: AuthenticatedCorretoresRoute,
  AuthenticatedEmpreendimentosRoute: AuthenticatedEmpreendimentosRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedPlantoesRoute: AuthenticatedPlantoesRoute,
  AuthenticatedRoletaRoute: AuthenticatedRoletaRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CorretorRoute: CorretorRoute,
  GerenciaRoute: GerenciaRoute,
  LgpdRoute: LgpdRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  SetupRoute: SetupRoute,
  ApiPublicLorenzaRoute: ApiPublicLorenzaRoute,
  ApiPublicHooksAvisosRenovacaoRoute: ApiPublicHooksAvisosRenovacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
