/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotemRouteImport } from './routes/totem'
import { Route as SistemaRouteImport } from './routes/sistema'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlantaoRouteImport } from './routes/plantao'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as GerenciaRouteImport } from './routes/gerencia'
import { Route as CorretorRouteImport } from './routes/corretor'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedRoletaRouteImport } from './routes/_authenticated/roleta'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPresencasRouteImport } from './routes/_authenticated/presencas'
import { Route as AuthenticatedPlantoesRouteImport } from './routes/_authenticated/plantoes'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedEmpreendimentosRouteImport } from './routes/_authenticated/empreendimentos'
import { Route as AuthenticatedCorretoresRouteImport } from './routes/_authenticated/corretores'
import { Route as AuthenticatedCoordenadorRouteImport } from './routes/_authenticated/coordenador'
import { Route as AuthenticatedAtendimentosRouteImport } from './routes/_authenticated/atendimentos'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiPublicLorenzaRouteImport } from './routes/api/public/lorenza'
import { Route as ApiPublicHooksAvisosRenovacaoRouteImport } from './routes/api/public/hooks/avisos-renovacao'

const TotemRoute = TotemRouteImport.update({
  id: '/totem',
  path: '/totem',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemaRoute = SistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantaoRoute = PlantaoRouteImport.update({
  id: '/plantao',
  path: '/plantao',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciaRoute = GerenciaRouteImport.update({
  id: '/gerencia',
  path: '/gerencia',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorRoute = CorretorRouteImport.update({
  id: '/corretor',
  path: '/corretor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoletaRoute = AuthenticatedRoletaRouteImport.update({
  id: '/roleta',
  path: '/roleta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPresencasRoute = AuthenticatedPresencasRouteImport.update({
  id: '/presencas',
  path: '/presencas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlantoesRoute = AuthenticatedPlantoesRouteImport.update({
  id: '/plantoes',
  path: '/plantoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpreendimentosRoute =
  AuthenticatedEmpreendimentosRouteImport.update({
    id: '/empreendimentos',
    path: '/empreendimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCorretoresRoute = AuthenticatedCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoordenadorRoute =
  AuthenticatedCoordenadorRouteImport.update({
    id: '/coordenador',
    path: '/coordenador',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAtendimentosRoute =
  AuthenticatedAtendimentosRouteImport.update({
    id: '/atendimentos',
    path: '/atendimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicLorenzaRoute = ApiPublicLorenzaRouteImport.update({
  id: '/api/public/lorenza',
  path: '/api/public/lorenza',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAvisosRenovacaoRoute =
  ApiPublicHooksAvisosRenovacaoRouteImport.update({
    id: '/api/public/hooks/avisos-renovacao',
    path: '/api/public/hooks/avisos-renovacao',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/corretor': typeof CorretorRoute
  '/gerencia': typeof GerenciaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/plantao': typeof PlantaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sistema': typeof SistemaRoute
  '/totem': typeof TotemRoute
  '/app': typeof AuthenticatedAppRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/coordenador': typeof AuthenticatedCoordenadorRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/plantoes': typeof AuthenticatedPlantoesRoute
  '/presencas': typeof AuthenticatedPresencasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/roleta': typeof AuthenticatedRoletaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/lorenza': typeof ApiPublicLorenzaRoute
  '/api/public/hooks/avisos-renovacao': typeof ApiPublicHooksAvisosRenovacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/corretor': typeof CorretorRoute
  '/gerencia': typeof GerenciaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/plantao': typeof PlantaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sistema': typeof SistemaRoute
  '/totem': typeof TotemRoute
  '/app': typeof AuthenticatedAppRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/coordenador': typeof AuthenticatedCoordenadorRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/plantoes': typeof AuthenticatedPlantoesRoute
  '/presencas': typeof AuthenticatedPresencasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/roleta': typeof AuthenticatedRoletaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/lorenza': typeof ApiPublicLorenzaRoute
  '/api/public/hooks/avisos-renovacao': typeof ApiPublicHooksAvisosRenovacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/apresentacao': typeof ApresentacaoRoute
  '/corretor': typeof CorretorRoute
  '/gerencia': typeof GerenciaRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/plantao': typeof PlantaoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sistema': typeof SistemaRoute
  '/totem': typeof TotemRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/_authenticated/coordenador': typeof AuthenticatedCoordenadorRoute
  '/_authenticated/corretores': typeof AuthenticatedCorretoresRoute
  '/_authenticated/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/plantoes': typeof AuthenticatedPlantoesRoute
  '/_authenticated/presencas': typeof AuthenticatedPresencasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/roleta': typeof AuthenticatedRoletaRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/lorenza': typeof ApiPublicLorenzaRoute
  '/api/public/hooks/avisos-renovacao': typeof ApiPublicHooksAvisosRenovacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apresentacao'
    | '/corretor'
    | '/gerencia'
    | '/lgpd'
    | '/login'
    | '/planos'
    | '/plantao'
    | '/reset-password'
    | '/setup'
    | '/sistema'
    | '/totem'
    | '/app'
    | '/atendimentos'
    | '/coordenador'
    | '/corretores'
    | '/empreendimentos'
    | '/integracoes'
    | '/mensagens'
    | '/plantoes'
    | '/presencas'
    | '/relatorios'
    | '/roleta'
    | '/usuarios'
    | '/api/public/lorenza'
    | '/api/public/hooks/avisos-renovacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apresentacao'
    | '/corretor'
    | '/gerencia'
    | '/lgpd'
    | '/login'
    | '/planos'
    | '/plantao'
    | '/reset-password'
    | '/setup'
    | '/sistema'
    | '/totem'
    | '/app'
    | '/atendimentos'
    | '/coordenador'
    | '/corretores'
    | '/empreendimentos'
    | '/integracoes'
    | '/mensagens'
    | '/plantoes'
    | '/presencas'
    | '/relatorios'
    | '/roleta'
    | '/usuarios'
    | '/api/public/lorenza'
    | '/api/public/hooks/avisos-renovacao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apresentacao'
    | '/corretor'
    | '/gerencia'
    | '/lgpd'
    | '/login'
    | '/planos'
    | '/plantao'
    | '/reset-password'
    | '/setup'
    | '/sistema'
    | '/totem'
    | '/_authenticated/app'
    | '/_authenticated/atendimentos'
    | '/_authenticated/coordenador'
    | '/_authenticated/corretores'
    | '/_authenticated/empreendimentos'
    | '/_authenticated/integracoes'
    | '/_authenticated/mensagens'
    | '/_authenticated/plantoes'
    | '/_authenticated/presencas'
    | '/_authenticated/relatorios'
    | '/_authenticated/roleta'
    | '/_authenticated/usuarios'
    | '/api/public/lorenza'
    | '/api/public/hooks/avisos-renovacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApresentacaoRoute: typeof ApresentacaoRoute
  CorretorRoute: typeof CorretorRoute
  GerenciaRoute: typeof GerenciaRoute
  LgpdRoute: typeof LgpdRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  PlantaoRoute: typeof PlantaoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SistemaRoute: typeof SistemaRoute
  TotemRoute: typeof TotemRoute
  ApiPublicLorenzaRoute: typeof ApiPublicLorenzaRoute
  ApiPublicHooksAvisosRenovacaoRoute: typeof ApiPublicHooksAvisosRenovacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totem': {
      id: '/totem'
      path: '/totem'
      fullPath: '/totem'
      preLoaderRoute: typeof TotemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistema': {
      id: '/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof SistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantao': {
      id: '/plantao'
      path: '/plantao'
      fullPath: '/plantao'
      preLoaderRoute: typeof PlantaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencia': {
      id: '/gerencia'
      path: '/gerencia'
      fullPath: '/gerencia'
      preLoaderRoute: typeof GerenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor': {
      id: '/corretor'
      path: '/corretor'
      fullPath: '/corretor'
      preLoaderRoute: typeof CorretorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roleta': {
      id: '/_authenticated/roleta'
      path: '/roleta'
      fullPath: '/roleta'
      preLoaderRoute: typeof AuthenticatedRoletaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/presencas': {
      id: '/_authenticated/presencas'
      path: '/presencas'
      fullPath: '/presencas'
      preLoaderRoute: typeof AuthenticatedPresencasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plantoes': {
      id: '/_authenticated/plantoes'
      path: '/plantoes'
      fullPath: '/plantoes'
      preLoaderRoute: typeof AuthenticatedPlantoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empreendimentos': {
      id: '/_authenticated/empreendimentos'
      path: '/empreendimentos'
      fullPath: '/empreendimentos'
      preLoaderRoute: typeof AuthenticatedEmpreendimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corretores': {
      id: '/_authenticated/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AuthenticatedCorretoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coordenador': {
      id: '/_authenticated/coordenador'
      path: '/coordenador'
      fullPath: '/coordenador'
      preLoaderRoute: typeof AuthenticatedCoordenadorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atendimentos': {
      id: '/_authenticated/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AuthenticatedAtendimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/lorenza': {
      id: '/api/public/lorenza'
      path: '/api/public/lorenza'
      fullPath: '/api/public/lorenza'
      preLoaderRoute: typeof ApiPublicLorenzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/avisos-renovacao': {
      id: '/api/public/hooks/avisos-renovacao'
      path: '/api/public/hooks/avisos-renovacao'
      fullPath: '/api/public/hooks/avisos-renovacao'
      preLoaderRoute: typeof ApiPublicHooksAvisosRenovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedAtendimentosRoute: typeof AuthenticatedAtendimentosRoute
  AuthenticatedCoordenadorRoute: typeof AuthenticatedCoordenadorRoute
  AuthenticatedCorretoresRoute: typeof AuthenticatedCorretoresRoute
  AuthenticatedEmpreendimentosRoute: typeof AuthenticatedEmpreendimentosRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedPlantoesRoute: typeof AuthenticatedPlantoesRoute
  AuthenticatedPresencasRoute: typeof AuthenticatedPresencasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedRoletaRoute: typeof AuthenticatedRoletaRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedAtendimentosRoute: AuthenticatedAtendimentosRoute,
  AuthenticatedCoordenadorRoute: AuthenticatedCoordenadorRoute,
  AuthenticatedCorretoresRoute: AuthenticatedCorretoresRoute,
  AuthenticatedEmpreendimentosRoute: AuthenticatedEmpreendimentosRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedPlantoesRoute: AuthenticatedPlantoesRoute,
  AuthenticatedPresencasRoute: AuthenticatedPresencasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedRoletaRoute: AuthenticatedRoletaRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApresentacaoRoute: ApresentacaoRoute,
  CorretorRoute: CorretorRoute,
  GerenciaRoute: GerenciaRoute,
  LgpdRoute: LgpdRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  PlantaoRoute: PlantaoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SistemaRoute: SistemaRoute,
  TotemRoute: TotemRoute,
  ApiPublicLorenzaRoute: ApiPublicLorenzaRoute,
  ApiPublicHooksAvisosRenovacaoRoute: ApiPublicHooksAvisosRenovacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
