/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPlantoesRouteImport } from './routes/_authenticated/plantoes'
import { Route as AuthenticatedEmpreendimentosRouteImport } from './routes/_authenticated/empreendimentos'
import { Route as AuthenticatedCorretoresRouteImport } from './routes/_authenticated/corretores'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlantoesRoute = AuthenticatedPlantoesRouteImport.update({
  id: '/plantoes',
  path: '/plantoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmpreendimentosRoute =
  AuthenticatedEmpreendimentosRouteImport.update({
    id: '/empreendimentos',
    path: '/empreendimentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCorretoresRoute = AuthenticatedCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedAppRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/plantoes': typeof AuthenticatedPlantoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedAppRoute
  '/corretores': typeof AuthenticatedCorretoresRoute
  '/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/plantoes': typeof AuthenticatedPlantoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/corretores': typeof AuthenticatedCorretoresRoute
  '/_authenticated/empreendimentos': typeof AuthenticatedEmpreendimentosRoute
  '/_authenticated/plantoes': typeof AuthenticatedPlantoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/corretores'
    | '/empreendimentos'
    | '/plantoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/app' | '/corretores' | '/empreendimentos' | '/plantoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/app'
    | '/_authenticated/corretores'
    | '/_authenticated/empreendimentos'
    | '/_authenticated/plantoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plantoes': {
      id: '/_authenticated/plantoes'
      path: '/plantoes'
      fullPath: '/plantoes'
      preLoaderRoute: typeof AuthenticatedPlantoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empreendimentos': {
      id: '/_authenticated/empreendimentos'
      path: '/empreendimentos'
      fullPath: '/empreendimentos'
      preLoaderRoute: typeof AuthenticatedEmpreendimentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corretores': {
      id: '/_authenticated/corretores'
      path: '/corretores'
      fullPath: '/corretores'
      preLoaderRoute: typeof AuthenticatedCorretoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCorretoresRoute: typeof AuthenticatedCorretoresRoute
  AuthenticatedEmpreendimentosRoute: typeof AuthenticatedEmpreendimentosRoute
  AuthenticatedPlantoesRoute: typeof AuthenticatedPlantoesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCorretoresRoute: AuthenticatedCorretoresRoute,
  AuthenticatedEmpreendimentosRoute: AuthenticatedEmpreendimentosRoute,
  AuthenticatedPlantoesRoute: AuthenticatedPlantoesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
